# Generated by Django 4.2.5 on 2023-09-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='caption',
            field=models.CharField(default='new tag', max_length=20),
        ),
    ]
